$(document).ready(function(){

    // vars
    var $body = $('body');
    var $articleImage = $('article img');

    // init
    $articleImage.on('click', addLayer);

    // add layer
    function addLayer (){

        // Check if the function works
        // alert('adding layer *Bzzzz bzzzz*');

        // Fetch the url from the clicked image.
        var $that = $(this);
        var $url = $that.prop('src');

        // Check the url
        // alert($url+' *Bzzzz bzzzz*');

        $('body').append('<div class="layer"><img src="'+$url+'"><div class="pull-right closeLayer" id="closeLayer">[X]</div></div>');

        // Remove layer 
        $('.closeLayer').on('click', function(){
            $('.layer').remove();
        });
    }

     var $thoughtsOfTheDay = [
        'A broad mind lacks focus.',
        'A coward always seeks compromise', 
        'A fine mind is a blessing of the Emperor - It should not be cluttered with trivialities.', 
        'A hundred thousand worlds, ten hundred thousand wars. There is no respite, there is nowhere to hide. Across the galaxy there is only war.', 
        'A logical argument must be dismissed with absolute conviction!', 
        'A mind without purpose will wander in dark places', 
        'A moment of laxity spawns a lifetime of heresy.', 
        'A questioning servant is more dangerous than an ignorant heretic', 
        'A single thought of heresy can blight a lifetime of faithful duty.', 
        'A small mind is a tidy mind.', 
        'A small mind is easily filled with faith.', 
        'A suspicious mind is a healthy mind', 
        'A warrior\'s faith in his commander is his best armour and his strongest weapon.', 
        'A weapon cannot substitute for zeal', 
        'Abhor the Night, it is the Light that Endures!',
        'Accept your lot!', 
        'Across the void of space men live as they have lived for millennia upon the sand, rock and soil of worlds bathed in the light of alien suns. So is Humanity\'s seed cast far and wide beyond the knowledge of Man, to thrive bitterly in the darkness, to take root and cling with robust and savage determination.', 
        'Adamantium walls and plasteel bulkheads may seem formidable, but an unshakeable faith in the Immortal Emperor of Man can overcome any barriers.', 
        'All Daemons are Falsehood. They are lies given the shape of creatures by the fell power of Chaos.', 
        'All mortal life is folly that does not feed the spirit', 
        'All souls cry out for salvation.',
        'An Empty Mind Is A Loyal Mind', 
        'An open mind is like a fortress with its gate unbarred and unguarded.', 
        'An unprotected soul can no more cross the storms of the warp than a heretic can bear the gaze of the Inquisition', 
        'Analysis is the bane of conviction', 
        'Appeasement is a curse', 
        'As the mind to the body so the soul to the spirit, as death to the mortal man so failure to the immortal, such is the price of all ambition.', 
        'Be courageous and bold, be humble before your masters, lead with valour! These things above all others will be of use when your time comes to die.',
        'Be grateful of your Master\'s favour!', 
        'Be Pure.', 
        'Be strong in your ignorance.', 
        'Be vigilant and strong. The Emperor knows what evil lurks in the vacillation of a weak fool.', 
        'Better crippled in body than corrupt in mind.', 
        'Between the stars the ancient unseen enemies of mankind wait and hunger. Every voyage into the nothing is a confrontation with horror, with the implacable things of the warp, and with man\'s own innermost fears.', 
        'Big guns never tire.',
        'Blessed are the Gun Makers.', 
        'Blessed is the mind too small for doubt', 
        'Blind faith is a just cause.', 
        'Brave are they who know everything yet fear nothing', 
        'Burn the heretic, Burn the Heretic! Kill the Mutant!', 
        'Purge the Unclean!', 
        'Burn the Unclean with the fires of Purity.',
        'By the manner of our death are we judged.', 
        'By the manner of their death we shall know them.', 
        'Call no man happy until he is dead.', 
        'Carry the Emperor\'s will as your torch, with it destroy the shadows', 
        'Cast out the mutant, the traitor, the heretic. For every enemy without there are a hundred within.', 
        'Cease and repent!', 
        'Cease purpose and die.',
        'Compromise is akin to treachery', 
        'Consider the Predator. Let your soul be armoured with Faith, driven on the tracks of Obedience which overcome all obstacles, and armed with the three great guns of Zeal, Duty and Purity.', 
        'Contemplation is the womb of treachery', 
        'Curse now the death in vain.', 
        'Damnation is eternal.', 
        'Dark dreams lie upon the heart', 
        'Death brings its own reward.',
        'Death is honor', 
        'Death is the only answer', 
        'Death is the servant of the righteous.', 
        'Defile not his presence', 
        'Defile the Mutant.', 
        'Destroy, destroy, destroy!', 
        'Dib dib dib, dob dob dob.',
        'Do not question the Will of the Emperor!', 
        'Do Not Wait for Death.', 
        'Do not waste your tears. I was not born to watch the world grow dim. Life is not measured in years, but by the deeds of men.',
        'Doubt is a sign of weakness', 
        'Drink deep of victory and remember the fallen.', 
        'Drink deep of victory and remember the fallen.',
        'Even a man who has nothing can still offer his life.', 
        'Every human life is a spark in the darkness. It flares for a moment, catches the eye, and is gone forever. A retinal after-image that fades and is obscured forever by newer, brighter lights.', 
        'Every lone spirit doubts his strength',
        'Every man is a spark in the darkness. By the time he is noticed he is gone forever. A retinal after-image that fades and is obscured by newer, brighter lights.', 
        'Examine your thoughts!', 
        'Excuses are the refuge of the weak',
        'Exist for the Emperor.', 
        'Facts are chains that bind perception and fetter truth. For a man can remake the world if he has a dream and no facts to cloud his mind.', 
        'Faith grows from the barrel of a gun.',
        'Faith, Hate and Ignorance', 
        'Faith. Honour. Vigilance.', 
        'Faith in the Emperor is its own reward',
        'Faith is the strongest shield.', 
        'Faith is your shield.', 
        'Faith without deeds is worthless.',
        'Fear is the Mind Killer.', 
        'Fear not the creatures of the jungle but those that lurk within your mind.', 
        'Fear the shadows; despise the night. There are horrors that no man can face and survive.',
        'Foolish are those who fear nothing, yet claim to know everything', 
        'For a warrior the only crime is cowardice.', 
        'For every battle honour, a thousand heroes die alone, unsung, and unremembered.',
        'For those who seek perfection - there can be no rest this side of the grave', 
        'For those who seek perfection there can be no rest this side of the grave', 
        'Forgiveness is a sign of weakness.',
        'Glory in death is life Eternal ', 
        'Happiness is a delusion of the weak', 
        'Hard work conquers everything.',
        'Hate enriches', 
        'Hatred is our surest weapon.', 
        'Hatred is the Emperor\'s greatest gift to humanity.',
        'He bears the weight of Mankind\'s ills', 
        'He who lives for nothing is nothing. He who dies for the Emperor is a hero.    ', 
        'Heresy grows from idleness',
        'Heresy must be met with hatred.', 
        'His will be done.', 
        'His Word is Our Strength.',
        'Honor your Chapter.', 
        'Honour, Duty & Obedience.',
        'Hope is the beginning of unhappiness.',
        'Hope is the first step on the road to disappointment.',
        'If a job\'s worth doing it\'s worth dying for!',
        'If a man dies that another should live, that man\'s spirit shall eat at the Emperor\'s table',
        'If you cannot speak well of your Master, be silent!',
        'Ignorance is a virtue',
        'Ignorance is bliss',
        'Ignorance is your best defence.',
        'In an hour of Darkness a blind man is the best guide. In an age of Insanity look to the madman to show the way.',
        'In the blazing furnace of battle we shall forge anew the iron will of yet a stronger race.',
        'In the darkness a blind man is the best guide. In an age of Madness look to the madman to show the way.',
        'Information Is Power',
        'Innocence proves nothing',
        'Inspiration grows from the barrel of a gun.',
        'Intellect is a mask for traitors',
        'Intolerance is a blessing',
        'It is better to die for the Emperor than to live for yourself.',
        'It is not in my mind to ask questions that cannot be answered. That is the soul standing upon the crossroad of vacillation. You search for wisdom, but achieve only a stasis of will.',
        'It is the bitter tears that the Gods weep that bind us to their hearts',
        'It is not the Horror of War that troubles me but the Unseen Horrors of Peace.',
        'Kill the mutant',
        'Know No Fear.',
        'Know the mutant; kill the mutant.',
        'Know thine enemy',
        'Knowledge is half the battle.',
        'Knowledge is power, hide it well.',
        'Knowledge is to be feared!',
        'Know your destination before you set out',
        'Know your duty!',
        'Labour long in his sight.',
        'Leniency is a sign of weakness!',
        'Let faith protect your mind and metal your flesh',
        'Let your soul be armoured with Faith, driven on the tracks of Obedience which overcome all obstacles, and armed with the three great guns of Zeal, Duty and Purity.',
        'Life is a prison, death a release',
        'Life is a prison, death shall be my release',
        'Life is the Emperor\'s currency, spend it well',
        'Listen not to the alien, look not upon the alien, speak not unto the alien!',
        'Look to your wargear!',
        'Look upon the Emperor\'s Works and tremble!',
        'Losses are acceptable. Failure is not.',
        'Mankind stands on the shoulders of the Martyred',
        'May the Emperor\'s Wrath forever cleanse our souls',
        'Mercy is a sign of weakness.',
        'My armour is contempt.',
        'Negotiation is surrender',
        'Never forget, never forgive.',
        'No army is big enough to conquer the galaxy. But faith alone can overturn the universe.',
        'No man died in His service that died in vain.',
        'No man died in the Emperor\'s service that died in vain',
        'No man that died in the Emperor\'s service died in vain.',
        'No Mercy. No Remorse. Just Kill.   ',
        'No pity! No remorse! No fear!',
        'Nobody is innocent, there are merely varying levels of guilt.',
        'Not Even The Dead Know The End Of War',
        'Nothing Can Hide From The Wrath Of The Emperor.',
        'Obedience is blind.',
        'Obedience is not enough.',
        'Official! The graves of wariors who have given their lives for the Emperor now outnumber the stars themselves.',
        'Only in death does duty end.',
        'Only the awkward question; only the foolish ask twice.',
        'Only the insane have strength enough to prosper.',
        'Only the insane have strength enough to prosper; only those that prosper truly judge what is sane.',
        'Only the insane have strength enough to prosper. Only those who prosper may truly judge what is sane.',
        'Only the insane prosper',
        'Only The Lost Understand True Terror',
        'Only those that follow the guiding light of the Emperor may save their souls.',
        'Pain is an illusion of the senses, despair an illusion of the mind',
        'Pain is an illusion of the senses, despair is an illusion of the mind.',
        'Peace is Hell.',
        'Perseverance and silence are the highest virtues',
        'Pity ye Not!',
        'Place your trust in the Emperor\'s steel',
        'Power resides in the will of the Righteous',
        'Praise the sun that brings the dawn of our final doom.',
        'Prayer cleanses the soul, but pain cleanses the body',
        'Pure in body, pure in heart',
        'Purge the unclean.',
        'Purge those who are unclean',
        'Reason begets doubt; Doubt begets heresy.',
        'Reason is the cloak of Traitors',
        'Rejoice in service!',
        'Revere the Omnissiah, for it is the source of all power.',
        'Ruthlessness is the kindness of the wise',
        'Save & Destroy.',
        'Seek no reward but the satisfaction of your Master!',
        'Seek honour as you act, and you will know no fear.',
        'Serve the Emperor today - tomorrow you may be dead!',
        'Serve the Emperor today, tomorrow you may be dead.',
        'Sins hidden in the heart turn all into decay.',
        'Sometimes the good must perish so that the rest survive. The lot of courage is to be sacrificed upon the altar of battle.',
        'Sorrow awaits the foolhardy',
        'Speed the bolt that brings the end of enemy and friend.',
        'Step not from the path of the Emperor.',
        'Study the alien, the better to kill it',
        'Submit to His will',
        'Success is commemorated. Failure merely remembered.',
        'Success is measured in blood; yours or your enemy\'s.',
        'Survival is no birthright, but a prize wrested from an uncaring galaxy by forgotten heroes.'

        ];

        console.log('!');

        var $randomNumber = Math.floor(Math.random()*$thoughtsOfTheDay.length);

        console.log($thoughtsOfTheDay.length);

        $('#numberThoughtOfTheDay').text('- Thought of the day #'+$randomNumber+'.');
        $('#thoughtOfTheDay').text($thoughtsOfTheDay[$randomNumber]);
});